version: '3.8'

services:
  # 1. DATABASE (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: btl2_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MatKhauManh123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # 2. BACKEND (Python)
  backend:
    build: ./backend
    container_name: btl2_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=db
      - DB_NAME=BTL_HCSDL  # Tên DB trùng với file 01_create.sql
      - DB_USER=sa
      - DB_PASSWORD=MatKhauManh123!
    volumes:
      - ./backend:/app

  # 3. FRONTEND (React)
  frontend:
    build: ./frontend
    container_name: btl2_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  sql_data: