version: '3.8'

services:
  # 1. DATABASE (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: btl2_mysql
    cap_add:
      - SYS_NICE  # Tối ưu hiệu năng
    environment:
      - MYSQL_ROOT_PASSWORD=MatKhauManh123!
      - MYSQL_DATABASE=lmsdb
    ports:
      - "3306:3306" # Cổng mặc định của MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      # TỰ ĐỘNG CHẠY FILE SQL KHI KHỞI TẠO (Quan trọng)
      - ./src/database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # 2. BACKEND (Python)
  backend:
    build: ./backend
    container_name: btl2_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_NAME=lmsdb
      - DB_USER=root
      - DB_PASSWORD=MatKhauManh123!
    volumes:
      - ./backend:/app

  # 3. FRONTEND (React)
  frontend:
    build: ./frontend
    container_name: btl2_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  mysql_data: